name: fl_backdoor_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pyyaml
  - tqdm
  - pip
  - pip:
    - torch==2.1.0 --index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118
    - flwr[simulation]==1.26.1
    - streamlit==1.54.0
    - plotly
